# Generated by Django 3.2.25 on 2024-03-30 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Adddetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mining_industries', models.CharField(max_length=200)),
                ('rules_regulations1', models.CharField(max_length=200)),
                ('rules_regulations2', models.CharField(max_length=200)),
                ('rules_regulations3', models.CharField(max_length=200)),
                ('rules_regulations4', models.CharField(max_length=200)),
                ('rules_regulations5', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=10)),
                ('email', models.CharField(max_length=20)),
                ('add', models.TextField()),
            ],
        ),
    ]
