# Generated by Django 3.2.25 on 2024-04-28 18:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0002_auto_20240428_2328'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appointmentinfo',
            old_name='hospitalname',
            new_name='bookname',
        ),
        migrations.RenameField(
            model_name='appointmentinfo',
            old_name='location',
            new_name='sem_year',
        ),
    ]
