# Generated by Django 3.2.25 on 2024-04-28 18:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0003_auto_20240428_2358'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Appointmentinfo',
            new_name='Bookinfo',
        ),
    ]
